import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.cars': 'Voitures',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.profile': 'Profil',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    
    // Hero
    'hero.badge': 'Location de voitures premium',
    'hero.title': 'Vivez la route comme',
    'hero.titleHighlight': 'jamais auparavant',
    'hero.subtitle': 'Louez le véhicule idéal pour vos trajets personnels ou professionnels. Des tarifs clairs, une réservation rapide et un service fiable.',
    'hero.cta': 'Parcourir les voitures',
    
    // Home
    'home.featured': 'En vedette',
    'home.popularCars': 'Voitures populaires',
    'home.viewAll': 'Voir tout',
    'home.noCars': 'Aucune voiture pour le moment. Ajoutez-en depuis le tableau de bord Admin.',
    'home.footer': '© 2026 Sihabi Cars. Tous droits réservés.',
    
    // Footer
    'footer.description': 'Nous sommes une société marocaine de location de voitures. Notre agence vous propose une gamme complète et variée de véhicules pour répondre à vos besoins de mobilité.',
    'footer.usefulLinks': 'Liens utiles',
    'footer.aboutUs': 'Qui sommes-nous ?',
    'footer.terms': 'Conditions générales',
    'footer.privacy': 'Politique de confidentialité',
    'footer.quickLinks': 'Accès rapide',
    'footer.contact': 'Contact',
    'footer.payment': 'Moyens de paiement',
    'footer.paymentCards': 'Visa & Mastercard',
    'footer.paymentCash': 'Espèces à la prise en charge',
    'footer.paymentTransfer': 'Virement bancaire',
    'footer.followUs': 'Suivez-nous',
    
    // Cars
    'cars.title': 'Voitures disponibles',
    'currency': 'DH',
    'cars.perDay': '/jour',
    'cars.day': 'jour',
    'cars.viewDetails': 'Voir les détails',
    'cars.bookNow': 'Réserver maintenant',
    'cars.features': 'Caractéristiques',
    'cars.specifications': 'Spécifications',
    'cars.available': 'Disponible',
    'cars.unavailable': 'Indisponible',
    'cars.seats': 'places',
    
    // Booking
    'booking.title': 'Réserver cette voiture',
    'booking.startDate': 'Date de début',
    'booking.endDate': 'Date de fin',
    'booking.totalPrice': 'Prix total',
    'booking.days': 'jours',
    'booking.confirm': 'Confirmer la réservation',
    'booking.success': 'Réservation confirmée avec succès!',
    'booking.error': 'Erreur lors de la réservation',
    'booking.loginRequired': 'Veuillez vous connecter pour réserver',
    'booking.cin': 'CIN',
    'booking.cinPlaceholder': 'Numéro CIN',
    'booking.driverLicense': 'Permis de conduire',
    'booking.driverLicensePlaceholder': 'Numéro de permis',
    'booking.paymentMethod': 'Méthode de paiement préférée',
    'booking.paymentNote': 'Le paiement sera effectué lors de la prise en charge du véhicule',
    'booking.cash': 'Espèces',
    'booking.card': 'Carte bancaire',
    
    // Profile
    'profile.title': 'Mon profil',
    'profile.edit': 'Modifier',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.city': 'Ville',
    'profile.myBookings': 'Mes réservations',
    'profile.noBookings': 'Aucune réservation',
    'profile.booking': 'Réservation',
    'profile.bookings': 'Réservations',
    'profile.bookingId': 'Réservation #',
    'profile.dates': 'Dates',
    'profile.total': 'Total',
    'profile.payment': 'Paiement',
    'profile.rentalPeriod': 'Période de location',
    'profile.to': 'à',
    'profile.totalPrice': 'Prix total',
    'profile.paymentMethod': 'Méthode de paiement',
    'profile.bookedOn': 'Réservé le',
    'profile.status.pending': 'En attente',
    'profile.status.confirmed': 'Confirmé',
    'profile.status.completed': 'Terminé',
    'profile.status.cancelled': 'Annulé',
    'profile.bookingConfirmed': 'Réservation confirmée',
    'profile.bookingConfirmedText': 'Cette réservation a été confirmée par l\'administrateur. Pour annuler, veuillez nous contacter à',
    'profile.orCall': 'ou appeler',
    'profile.cancelBooking': 'Annuler la réservation',
    'profile.keepBooking': 'Conserver la réservation',
    'profile.cancelBookingTitle': 'Annuler la réservation ?',
    'profile.cancelBookingConfirm': 'Êtes-vous sûr de vouloir annuler cette réservation pour',
    'profile.cancelBookingWarning': 'Cette action ne peut pas être annulée.',
    'profile.yesCancelBooking': 'Oui, annuler la réservation',
    'profile.bookingCancelledSuccess': 'Réservation annulée avec succès !',
    'profile.bookingCancelledError': 'Échec de l\'annulation de la réservation',
    
    // Auth
    'auth.account': 'Compte',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.register': "S'inscrire",
    'auth.createAccount': 'Créer un compte',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phone': 'Téléphone',
    'auth.city': 'Ville',
    'auth.passwordMin': 'Min. 8 caractères',
    'auth.phonePlaceholder': '+212 6XX XXX XXX',
    'auth.noAccount': "Vous n'avez pas de compte ?",
    'auth.registerHere': 'Inscrivez-vous ici',
    'auth.haveAccount': 'Vous avez déjà un compte ?',
    'auth.loginHere': 'Connectez-vous ici',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.forgotPasswordSubtitle': 'Entrez votre email et nous vous enverrons un lien de réinitialisation',
    'auth.sendResetLink': 'Envoyer le lien',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.emailSent': 'Vérifiez votre email',
    'auth.emailSentMessage': 'Nous avons envoyé un lien de réinitialisation à',
    'auth.emailSentNote': 'Cliquez sur le lien dans l\'email pour réinitialiser votre mot de passe. Le lien expirera dans 1 heure.',
    'auth.resetPassword': 'Réinitialiser le mot de passe',
    'auth.resetPasswordSubtitle': 'Entrez votre nouveau mot de passe ci-dessous',
    'auth.newPassword': 'Nouveau mot de passe',
    'auth.invalidLink': 'Lien invalide',
    'auth.invalidLinkMessage': 'Ce lien de réinitialisation est invalide ou a expiré. Veuillez en demander un nouveau.',
    'auth.requestNewLink': 'Demander un nouveau lien',
    'auth.passwordReset': 'Mot de passe réinitialisé !',
    'auth.passwordResetMessage': 'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    
    // Admin
    'admin.title': 'Tableau de bord Admin',
    'admin.analytics': 'Analytiques',
    'admin.carsTab': 'Voitures',
    'admin.bookingsTab': 'Réservations',
    'admin.usersTab': 'Utilisateurs',
    'admin.messagesTab': 'Messages',
    'admin.cars': 'Gestion des voitures',
    'admin.bookings': 'Gestion des réservations',
    'admin.addCar': 'Ajouter une voiture',
    'admin.addNewCar': 'Ajouter une nouvelle voiture',
    'admin.editCar': 'Modifier la voiture',
    'admin.saveCar': 'Enregistrer la voiture',
    'admin.saving': 'Enregistrement...',
    'admin.saveChanges': 'Enregistrer les modifications',
    'admin.edit': 'Modifier',
    'admin.delete': 'Supprimer',
    'admin.brand': 'Marque',
    'admin.name': 'Nom',
    'admin.price': 'Prix',
    'admin.actions': 'Actions',
    'admin.dailyRevenue': 'Revenu journalier',
    'admin.today': "Aujourd'hui",
    'admin.yesterday': 'Hier',
    'admin.monthlyRevenue': 'Revenu mensuel',
    'admin.thisMonth': 'Ce mois',
    'admin.lastMonth': 'Mois dernier',
    'admin.yearlyRevenue': 'Revenu annuel',
    'admin.thisYear': 'Cette année',
    'admin.lastYear': "L'année dernière",
    'admin.totalRevenue': 'Revenu total',
    'admin.allTime': 'Depuis toujours',
    'admin.totalBookings': 'Total réservations',
    'admin.totalUsers': 'Total utilisateurs',
    'admin.totalCars': 'Total voitures',
    'admin.car': 'Voiture',
    'admin.category': 'Catégorie',
    'admin.status': 'Statut',
    'admin.available': 'Disponible',
    'admin.unavailable': 'Indisponible',
    'admin.featuredHomepage': 'En vedette sur la page d\'accueil',
    'admin.imageUrl': 'URL de l\'image',
    'admin.uploadImages': 'Télécharger des images',
    'admin.description': 'Description',
    'admin.seats': 'Places',
    'admin.transmission': 'Transmission',
    'admin.automatic': 'Automatique',
    'admin.manual': 'Manuelle',
    'admin.fuelType': 'Carburant',
    'admin.gasoline': 'Essence',
    'admin.diesel': 'Diesel',
    'admin.electric': 'Électrique',
    'admin.hybrid': 'Hybride',
    'admin.noCars': 'Aucune voiture pour le moment',
    'admin.customer': 'Client',
    'admin.dates': 'Dates',
    'admin.total': 'Total',
    'admin.payment': 'Paiement',
    'admin.cash': 'Espèces',
    'admin.card': 'Carte',
    'admin.pending': 'En attente',
    'admin.confirmed': 'Confirmé',
    'admin.completed': 'Terminé',
    'admin.noBookings': 'Aucune réservation pour le moment',
    'admin.noBookingsSearch': 'Aucune réservation ne correspond à votre recherche',
    'admin.searchBookings': 'Rechercher par client, voiture ou ID...',
    'admin.refresh': 'Actualiser',
    'admin.customerInfo': 'Informations client',
    'admin.bookingDetails': 'Détails de la réservation',
    'admin.bookingId': 'ID réservation',
    'admin.totalPrice': 'Prix total',
    'admin.contactInfo': 'Informations de contact',
    'admin.emailLabel': 'Email',
    'admin.phone': 'Téléphone',
    'admin.registeredUser': 'Compte utilisateur enregistré',
    'admin.accountName': 'Nom du compte',
    'admin.accountEmail': 'Email du compte',
    'admin.accountPhone': 'Téléphone du compte',
    'admin.city': 'Ville',
    'admin.bookedOn': 'Réservé le',
    'admin.user': 'Utilisateur',
    'admin.contact': 'Contact',
    'admin.role': 'Rôle',
    'admin.roleUser': 'Utilisateur',
    'admin.roleAdmin': 'Admin',
    'admin.bookingsCount': 'Réservations',
    'admin.totalSpent': 'Total dépensé',
    'admin.joined': 'Inscrit le',
    'admin.noUsers': 'Aucun utilisateur pour le moment',
    'admin.noUsersSearch': 'Aucun utilisateur ne correspond à votre recherche',
    'admin.searchUsers': 'Rechercher par nom, email ou ville...',
    'admin.editUser': 'Modifier l\'utilisateur',
    'admin.statistics': 'Statistiques',
    'admin.totalBookingsReadOnly': 'Total réservations (lecture seule)',
    'admin.totalSpentLabel': 'Total dépensé ($)',
    'admin.from': 'De',
    'admin.message': 'Message',
    'admin.date': 'Date',
    'admin.unread': 'Non lu',
    'admin.read': 'Lu',
    'admin.replied': 'Répondu',
    'admin.noMessages': 'Aucun message pour le moment',
    'admin.accountStatus': 'Statut du compte',
    'admin.accountActive': 'Actif',
    'admin.accountSuspended': 'Suspendu',
    'admin.accountBanned': 'Banni',
    'admin.changeStatus': 'Changer le statut',
    'admin.statusReason': 'Raison (Optionnel)',
    'admin.statusReasonPlaceholder': 'ex: Paiements échoués multiples, Violation des conditions, etc.',
    'admin.statusWarning': 'Cet utilisateur ne pourra pas se connecter tant qu\'il n\'est pas réactivé.',
    'admin.updateStatus': 'Mettre à jour le statut',
    'admin.updating': 'Mise à jour...',
    'admin.statusActiveDesc': 'Actif - Accès complet',
    'admin.statusSuspendedDesc': 'Suspendu - Temporairement bloqué',
    'admin.statusBannedDesc': 'Banni - Bloqué définitivement',
    'admin.charts': 'Graphiques',
    'admin.revenueGrowth': 'Croissance du revenu',
    'admin.vsLastMonth': 'vs mois dernier',
    'admin.repeatCustomers': 'Clients fidèles',
    'admin.avgBookings': 'réservations moy.',
    'admin.retentionRevenue': 'Revenu de fidélisation',
    'admin.fromRepeatCustomers': 'des clients fidèles',
    'admin.topCarRevenue': 'Revenu meilleure voiture',
    'admin.revenueTrend': 'Tendance des revenus (12 derniers mois)',
    'admin.weeklyRevenue': 'Revenu hebdomadaire (8 dernières semaines)',
    'admin.bookingsByStatus': 'Réservations par statut',
    'admin.mostProfitableCars': 'Voitures les plus rentables',
    'admin.paymentMethods': 'Méthodes de paiement',
    'admin.topRepeatCustomers': 'Meilleurs clients fidèles',
    'admin.customer': 'Client',
    'admin.bookingsColumn': 'Réservations',
    'admin.totalSpentColumn': 'Total dépensé',
    'admin.noRevenueData': 'Aucune donnée de revenu disponible',
    'admin.noWeeklyData': 'Aucune donnée hebdomadaire disponible',
    'admin.noBookingStatusData': 'Aucune donnée de statut de réservation',
    'admin.noCarBookingData': 'Aucune donnée de réservation de voiture disponible',
    'admin.noPaymentData': 'Aucune donnée de paiement disponible',
    'admin.noRepeatCustomers': 'Pas encore de clients fidèles',
    'admin.noAnalyticsData': 'Aucune donnée analytique disponible',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.address': 'Adresse',
    'contact.addressLine1': '132 Rue Ahmed Zakaria',
    'contact.addressLine2': 'Bloc Abtih Extension Dakhla, Agadir',
    'contact.email': 'Email',
    'contact.hours': 'Heures d\'ouverture',
    'contact.location': 'Notre emplacement',
    'contact.getDirections': 'Obtenir l\'itinéraire',
    'contact.findUs': 'Trouvez-nous',
    'contact.visitText': 'Visitez-nous à notre bureau de location de voitures. Nous sommes là pour vous aider à trouver le véhicule parfait.',
    'contact.getInTouch': 'Entrer en contact',
    'contact.contactUs': 'Contactez-nous',
    'contact.contactSubtitle': 'Vous avez des questions? Nous aimerions avoir de vos nouvelles. Envoyez-nous un message et nous vous répondrons dès que possible.',
    'contact.contactInfo': 'Informations de contact',
    'contact.phone': 'Téléphone',
    'contact.businessHours': 'Heures d\'ouverture',
    'contact.monday': 'Lundi - Vendredi',
    'contact.saturday': 'Samedi',
    'contact.sunday': 'Dimanche',
    'contact.sendMessage': 'Envoyez-nous un message',
    'contact.name': 'Nom',
    'contact.namePlaceholder': 'Votre nom',
    'contact.emailPlaceholder': 'votre.email@exemple.com',
    'contact.phonePlaceholder': '+212 XXX XXX XXX',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Dites-nous comment nous pouvons vous aider...',
    'contact.send': 'Envoyer le message',
    'contact.sending': 'Envoi...',
    'contact.success': 'Message envoyé! Nous vous répondrons bientôt.',
    'contact.error': 'Échec de l\'envoi du message. Veuillez réessayer.',
    
    // WhatsApp
    'whatsapp.contact': 'Contacter via WhatsApp',
    'whatsapp.hello': 'Bonjour, je suis intéressé par',
    
    // Cars Page
    'carsPage.title': 'Notre flotte',
    'carsPage.subtitle': 'Trouvez et réservez votre véhicule idéal',
    'carsPage.searchPlaceholder': 'Rechercher par nom ou marque...',
    'carsPage.noResults': 'Aucune voiture ne correspond à vos filtres.',
    'carsPage.all': 'Tous',
    
    // About
    'about.title': 'À propos de Votre Agence de Location',
    'about.subtitle': 'Votre partenaire de confiance pour la location de voitures au Maroc',
    'about.intro': 'Votre Agence de Location est une agence marocaine de location de voitures qui place le client au cœur de son activité. Nous proposons une flotte diversifiée (citadines, berlines, SUV, utilitaires) et des services adaptés : locations courte et moyenne durée, options avec chauffeur, et solutions pour entreprises.',
    'about.missionTitle': 'Notre mission',
    'about.mission1': 'Faciliter vos déplacements avec une réservation simple et rapide (en ligne ou par téléphone).',
    'about.mission2': 'Garantir des véhicules entretenus, fiables et assurés.',
    'about.mission3': 'Proposer des tarifs transparents et une assistance client proactive.',
    'about.whyTitle': 'Pourquoi nous choisir ?',
    'about.why1Title': 'Clarté des prix',
    'about.why1Text': 'Pas de frais cachés, devis détaillés avant validation.',
    'about.why2Title': 'Flexibilité',
    'about.why2Text': 'Large choix de catégories et d\'options (siège bébé, GPS, conducteur additionnel, etc.).',
    'about.why3Title': 'Support client',
    'about.why3Text': 'Une équipe à l\'écoute, joignable par email à sihabi.cars@gmail.com.',
    'about.qualityTitle': 'Engagement qualité & sécurité',
    'about.qualityText': 'Chaque véhicule est inspecté régulièrement. Nous respectons des standards élevés d\'hygiène et d\'entretien afin de garantir votre sécurité et votre confort.',
    'about.contactTitle': 'Nous contacter',
    'about.contactText': 'Des questions ou un besoin spécifique ? Écrivez-nous ou visitez notre site.',
    
    // Terms
    'terms.title': 'Conditions générales d\'utilisation',
    'terms.intro': 'En accédant au site web de Votre Agence de Location et en utilisant nos services de réservation en ligne, vous acceptez ces conditions.',
    'terms.section1Title': 'Objet',
    'terms.section1Text': 'Le site web permet de parcourir la flotte, d\'obtenir des prix et de soumettre des demandes de réservation. Certaines réservations nécessitent une confirmation manuelle.',
    'terms.section2Title': 'Compte et exactitude',
    'terms.section2Text': 'Vous êtes responsable de l\'exactitude des informations que vous fournissez. En cas d\'erreurs évidentes (prix/disponibilité), l\'Agence peut annuler la demande après vous en avoir informé.',
    'terms.section3Title': 'Processus de réservation',
    'terms.section3Item1': 'Demande en ligne avec vos informations et dates.',
    'terms.section3Item2': 'Vérification de la disponibilité.',
    'terms.section3Item3': 'Confirmation de l\'Agence (email/téléphone) et conditions détaillées (caution, documents, etc.).',
    'terms.section4Title': 'Tarification et paiement',
    'terms.section4Text': 'Les prix affichés sont indicatifs ; le montant final peut inclure des options/assurances sélectionnées. Les modes de paiement acceptés sont fournis lors de la confirmation.',
    'terms.section5Title': 'Annulation et modifications',
    'terms.section5Text': 'Les conditions d\'annulation/modification sont fournies lors de la confirmation (délais, frais éventuels).',
    'terms.section6Title': 'Utilisation du véhicule',
    'terms.section6Text': 'Respectez le code de la route, la politique de carburant, l\'entretien, l\'heure et le lieu de retour. Les amendes/dommages sont à la charge du locataire selon le contrat de location.',
    'terms.section7Title': 'Responsabilité',
    'terms.section7Text': 'Le site peut être indisponible (maintenance/force majeure). Votre Agence de Location n\'est pas responsable des dommages indirects liés à l\'utilisation du site.',
    'terms.section8Title': 'Données personnelles',
    'terms.section8Text': 'Le traitement des données suit notre Politique de confidentialité. Contact : sihabi.cars@gmail.com.',
    'terms.section9Title': 'Droit applicable',
    'terms.section9Text': 'Ces conditions sont régies par la loi applicable au siège social de l\'Agence.',
    
    // Privacy
    'privacy.title': 'Politique de confidentialité',
    'privacy.intro': 'Cette politique explique comment Votre Agence de Location collecte, utilise, partage et protège vos données personnelles lorsque vous utilisez notre site web et nos services de réservation en ligne.',
    'privacy.section1Title': 'Responsable du traitement',
    'privacy.section1Text': 'Votre Agence de Location, Maroc. Contact : sihabi.cars@gmail.com.',
    'privacy.section2Title': 'Données que nous collectons',
    'privacy.section2Item1': 'Identité et contact : nom, email, téléphone, adresse.',
    'privacy.section2Item2': 'Données de réservation : dates, lieux, catégorie de véhicule, options.',
    'privacy.section2Item3': 'Données de paiement : traitées par des fournisseurs sécurisés (nous ne stockons pas les numéros de carte).',
    'privacy.section2Item4': 'Données techniques : adresse IP, journaux, cookies (voir section cookies).',
    'privacy.section3Title': 'Finalités et bases légales',
    'privacy.section3Item1': 'Exécution du contrat : gestion des réservations, communication client.',
    'privacy.section3Item2': 'Obligations légales : facturation, comptabilité, prévention de la fraude.',
    'privacy.section3Item3': 'Intérêt légitime : amélioration du service, statistiques d\'utilisation.',
    'privacy.section3Item4': 'Consentement : emails marketing si vous y consentez (désinscription à tout moment).',
    'privacy.section4Title': 'Partage des données',
    'privacy.section4Text': 'Nous ne vendons pas de données personnelles. Nous pouvons les partager avec :',
    'privacy.section4Item1': 'Fournisseurs techniques (hébergement, paiement, email) strictement nécessaires pour fournir le service.',
    'privacy.section4Item2': 'Autorités publiques lorsque requis par la loi.',
    'privacy.section5Title': 'Conservation',
    'privacy.section5Text': 'Nous conservons les données aussi longtemps que nécessaire pour chaque finalité (par ex., conservation légale jusqu\'à 10 ans pour certains enregistrements), puis les archivons ou les supprimons de manière sécurisée.',
    'privacy.section6Title': 'Cookies',
    'privacy.section6Text': 'Nous utilisons des cookies techniques, analytiques et—le cas échéant—marketing. Vous pouvez gérer vos préférences dans votre navigateur.',
    'privacy.section7Title': 'Sécurité',
    'privacy.section7Text': 'Nous mettons en œuvre des mesures techniques et organisationnelles (chiffrement en transit, contrôles d\'accès, sauvegardes).',
    'privacy.section8Title': 'Vos droits',
    'privacy.section8Text': 'Accès, rectification, suppression, limitation, opposition, portabilité et directives post-mortem (selon applicable). Contact : sihabi.cars@gmail.com.',
    'privacy.section9Title': 'Transferts internationaux',
    'privacy.section9Text': 'Certains fournisseurs peuvent être situés à l\'étranger ; nous assurons des garanties appropriées (par ex., clauses contractuelles types).',
    'privacy.section10Title': 'Contact',
    'privacy.section10Text': 'Pour toute question relative à la confidentialité, envoyez un email à sihabi.cars@gmail.com.',
    
    'search.placeholder': 'Rechercher une voiture (marque, modèle...)',
    'search.category': 'Catégorie',
    'search.allCategories': 'Toutes catégories',
    'search.button': 'Rechercher',
    'stats.clients': '+200',
    'stats.clientsLabel': 'Clients satisfaits',
    'stats.cars': '+50',
    'stats.carsLabel': 'Véhicules disponibles',
    'stats.experience': '10 ans',
    'stats.experienceLabel': "D'expérience",
    'stats.cities': 'Agadir',
    'stats.citiesLabel': '& environs',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.cars': 'السيارات',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.admin': 'الإدارة',
    'nav.profile': 'الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'تسجيل الدخول',
    
    // Hero
    'hero.badge': 'تأجير سيارات فاخرة',
    'hero.title': 'قد سيارة',
    'hero.titleHighlight': 'أحلامك',
    'hero.subtitle': 'اختر من مجموعتنا من المركبات المميزة. من السيارات الفاخرة إلى السيارات الرياضية عالية الأداء.',
    'hero.cta': 'تصفح السيارات',
    
    // Home
    'home.featured': 'مميز',
    'home.popularCars': 'السيارات الشائعة',
    'home.viewAll': 'عرض الكل',
    'home.noCars': 'لا توجد سيارات حتى الآن. أضف بعضها من لوحة التحكم.',
    'home.footer': '© 2026 Sihabi CarsX. جميع الحقوق محفوظة.',
    
    // Footer
    'footer.description': 'نحن شركة مغربية لتأجير السيارات. تقدم وكالتنا مجموعة كاملة ومتنوعة من المركبات لتلبية احتياجاتك في التنقل.',
    'footer.usefulLinks': 'روابط مفيدة',
    'footer.aboutUs': 'من نحن؟',
    'footer.terms': 'الشروط والأحكام',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.quickLinks': 'وصول سريع',
    'footer.contact': 'اتصل',
    'footer.payment': 'طرق الدفع',
    'footer.paymentCards': 'فيزا وماستركارد',
    'footer.paymentCash': 'نقدًا عند الاستلام',
    'footer.paymentTransfer': 'تحويل بنكي',
    'footer.followUs': 'تابعنا',
    
    // Cars
    'cars.title': 'السيارات المتاحة',
    'currency': 'درهم',
    'cars.perDay': '/يوم',
    'cars.day': 'يوم',
    'cars.viewDetails': 'عرض التفاصيل',
    'cars.bookNow': 'احجز الآن',
    'cars.features': 'المميزات',
    'cars.specifications': 'المواصفات',
    'cars.available': 'متاح',
    'cars.unavailable': 'غير متاح',
    'cars.seats': 'مقاعد',
    
    // Booking
    'booking.title': 'احجز هذه السيارة',
    'booking.startDate': 'تاريخ البداية',
    'booking.endDate': 'تاريخ النهاية',
    'booking.totalPrice': 'السعر الإجمالي',
    'booking.days': 'أيام',
    'booking.confirm': 'تأكيد الحجز',
    'booking.success': 'تم تأكيد الحجز بنجاح!',
    'booking.error': 'خطأ في الحجز',
    'booking.loginRequired': 'يرجى تسجيل الدخول للحجز',
    'booking.cin': 'رقم البطاقة الوطنية',
    'booking.cinPlaceholder': 'رقم البطاقة الوطنية',
    'booking.driverLicense': 'رخصة السياقة',
    'booking.driverLicensePlaceholder': 'رقم رخصة السياقة',
    'booking.paymentMethod': 'طريقة الدفع المفضلة',
    'booking.paymentNote': 'سيتم الدفع عند استلام السيارة',
    'booking.cash': 'نقداً',
    'booking.card': 'بطاقة بنكية',
    
    // Profile
    'profile.title': 'ملفي الشخصي',
    'profile.edit': 'تعديل',
    'profile.save': 'حفظ',
    'profile.cancel': 'إلغاء',
    'profile.firstName': 'الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.city': 'المدينة',
    'profile.myBookings': 'حجوزاتي',
    'profile.noBookings': 'لا توجد حجوزات',
    'profile.booking': 'حجز',
    'profile.bookings': 'حجوزات',
    'profile.bookingId': 'حجز #',
    'profile.dates': 'التواريخ',
    'profile.total': 'الإجمالي',
    'profile.payment': 'الدفع',
    'profile.rentalPeriod': 'فترة الإيجار',
    'profile.to': 'إلى',
    'profile.totalPrice': 'السعر الإجمالي',
    'profile.paymentMethod': 'طريقة الدفع',
    'profile.bookedOn': 'تم الحجز في',
    'profile.status.pending': 'قيد الانتظار',
    'profile.status.confirmed': 'مؤكد',
    'profile.status.completed': 'مكتمل',
    'profile.status.cancelled': 'ملغى',
    'profile.bookingConfirmed': 'تم تأكيد الحجز',
    'profile.bookingConfirmedText': 'تم تأكيد هذا الحجز من قبل المسؤول. للإلغاء، يرجى الاتصال بنا على',
    'profile.orCall': 'أو الاتصال',
    'profile.cancelBooking': 'إلغاء الحجز',
    'profile.keepBooking': 'الاحتفاظ بالحجز',
    'profile.cancelBookingTitle': 'إلغاء الحجز؟',
    'profile.cancelBookingConfirm': 'هل أنت متأكد من رغبتك في إلغاء هذا الحجز لـ',
    'profile.cancelBookingWarning': 'لا يمكن التراجع عن هذا الإجراء.',
    'profile.yesCancelBooking': 'نعم، إلغاء الحجز',
    'profile.bookingCancelledSuccess': 'تم إلغاء الحجز بنجاح!',
    'profile.bookingCancelledError': 'فشل إلغاء الحجز',
    
    // Auth
    'auth.account': 'الحساب',
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.register': 'تسجيل',
    'auth.createAccount': 'إنشاء حساب',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.phone': 'الهاتف',
    'auth.city': 'المدينة',
    'auth.passwordMin': 'الحد الأدنى 8 أحرف',
    'auth.phonePlaceholder': '+212 6XX XXX XXX',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.registerHere': 'سجل هنا',
    'auth.haveAccount': 'هل لديك حساب بالفعل؟',
    'auth.loginHere': 'تسجيل الدخول هنا',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.forgotPasswordSubtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين',
    'auth.sendResetLink': 'إرسال الرابط',
    'auth.backToLogin': 'العودة إلى تسجيل الدخول',
    'auth.emailSent': 'تحقق من بريدك الإلكتروني',
    'auth.emailSentMessage': 'لقد أرسلنا رابط إعادة التعيين إلى',
    'auth.emailSentNote': 'انقر على الرابط في البريد الإلكتروني لإعادة تعيين كلمة المرور. سينتهي صلاحية الرابط خلال ساعة واحدة.',
    'auth.resetPassword': 'إعادة تعيين كلمة المرور',
    'auth.resetPasswordSubtitle': 'أدخل كلمة المرور الجديدة أدناه',
    'auth.newPassword': 'كلمة المرور الجديدة',
    'auth.invalidLink': 'رابط غير صالح',
    'auth.invalidLinkMessage': 'رابط إعادة التعيين هذا غير صالح أو منتهي الصلاحية. يرجى طلب رابط جديد.',
    'auth.requestNewLink': 'طلب رابط جديد',
    'auth.passwordReset': 'تم إعادة تعيين كلمة المرور!',
    'auth.passwordResetMessage': 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
    
    // Admin
    'admin.title': 'لوحة التحكم',
    'admin.analytics': 'التحليلات',
    'admin.carsTab': 'السيارات',
    'admin.bookingsTab': 'الحجوزات',
    'admin.usersTab': 'المستخدمون',
    'admin.messagesTab': 'الرسائل',
    'admin.cars': 'إدارة السيارات',
    'admin.bookings': 'إدارة الحجوزات',
    'admin.addCar': 'إضافة سيارة',
    'admin.addNewCar': 'إضافة سيارة جديدة',
    'admin.editCar': 'تعديل السيارة',
    'admin.saveCar': 'حفظ السيارة',
    'admin.saving': 'جاري الحفظ...',
    'admin.saveChanges': 'حفظ التغييرات',
    'admin.edit': 'تعديل',
    'admin.delete': 'حذف',
    'admin.brand': 'العلامة التجارية',
    'admin.name': 'الاسم',
    'admin.price': 'السعر',
    'admin.actions': 'الإجراءات',
    'admin.dailyRevenue': 'الإيراد اليومي',
    'admin.today': 'اليوم',
    'admin.yesterday': 'أمس',
    'admin.monthlyRevenue': 'الإيراد الشهري',
    'admin.thisMonth': 'هذا الشهر',
    'admin.lastMonth': 'الشهر الماضي',
    'admin.yearlyRevenue': 'الإيراد السنوي',
    'admin.thisYear': 'هذا العام',
    'admin.lastYear': 'العام الماضي',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.allTime': 'كل الأوقات',
    'admin.totalBookings': 'إجمالي الحجوزات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalCars': 'إجمالي السيارات',
    'admin.car': 'سيارة',
    'admin.category': 'الفئة',
    'admin.status': 'الحالة',
    'admin.available': 'متاح',
    'admin.unavailable': 'غير متاح',
    'admin.featuredHomepage': 'مميز في الصفحة الرئيسية',
    'admin.imageUrl': 'رابط الصورة',
    'admin.uploadImages': 'رفع الصور',
    'admin.description': 'الوصف',
    'admin.seats': 'المقاعد',
    'admin.transmission': 'ناقل الحركة',
    'admin.automatic': 'أوتوماتيك',
    'admin.manual': 'يدوي',
    'admin.fuelType': 'نوع الوقود',
    'admin.gasoline': 'بنزين',
    'admin.diesel': 'ديزل',
    'admin.electric': 'كهربائي',
    'admin.hybrid': 'هجين',
    'admin.noCars': 'لا توجد سيارات حتى الآن',
    'admin.customer': 'العميل',
    'admin.dates': 'التواريخ',
    'admin.total': 'الإجمالي',
    'admin.payment': 'الدفع',
    'admin.cash': 'نقدًا',
    'admin.card': 'بطاقة',
    'admin.pending': 'قيد الانتظار',
    'admin.confirmed': 'مؤكد',
    'admin.completed': 'مكتمل',
    'admin.noBookings': 'لا توجد حجوزات حتى الآن',
    'admin.noBookingsSearch': 'لا توجد حجوزات تطابق بحثك',
    'admin.searchBookings': 'البحث بالعميل أو السيارة أو المعرف...',
    'admin.refresh': 'تحديث',
    'admin.customerInfo': 'معلومات العميل',
    'admin.bookingDetails': 'تفاصيل الحجز',
    'admin.bookingId': 'معرف الحجز',
    'admin.totalPrice': 'السعر الإجمالي',
    'admin.contactInfo': 'معلومات الاتصال',
    'admin.emailLabel': 'البريد الإلكتروني',
    'admin.phone': 'الهاتف',
    'admin.registeredUser': 'حساب مستخدم مسجل',
    'admin.accountName': 'اسم الحساب',
    'admin.accountEmail': 'بريد الحساب',
    'admin.accountPhone': 'هاتف الحساب',
    'admin.city': 'المدينة',
    'admin.bookedOn': 'تم الحجز في',
    'admin.user': 'مستخدم',
    'admin.contact': 'اتصال',
    'admin.role': 'الدور',
    'admin.roleUser': 'مستخدم',
    'admin.roleAdmin': 'مدير',
    'admin.bookingsCount': 'الحجوزات',
    'admin.totalSpent': 'إجمالي الإنفاق',
    'admin.joined': 'انضم في',
    'admin.noUsers': 'لا يوجد مستخدمون حتى الآن',
    'admin.noUsersSearch': 'لا يوجد مستخدمون يطابقون بحثك',
    'admin.searchUsers': 'البحث بالاسم أو البريد أو المدينة...',
    'admin.editUser': 'تعديل المستخدم',
    'admin.statistics': 'الإحصائيات',
    'admin.totalBookingsReadOnly': 'إجمالي الحجوزات (للقراءة فقط)',
    'admin.totalSpentLabel': 'إجمالي الإنفاق ($)',
    'admin.from': 'من',
    'admin.message': 'الرسالة',
    'admin.date': 'التاريخ',
    'admin.unread': 'غير مقروء',
    'admin.read': 'مقروء',
    'admin.replied': 'تم الرد',
    'admin.noMessages': 'لا توجد رسائل حتى الآن',
    'admin.accountStatus': 'حالة الحساب',
    'admin.accountActive': 'نشط',
    'admin.accountSuspended': 'معلق',
    'admin.accountBanned': 'محظور',
    'admin.changeStatus': 'تغيير الحالة',
    'admin.statusReason': 'السبب (اختياري)',
    'admin.statusReasonPlaceholder': 'مثال: فشل دفعات متعددة، انتهاك الشروط، إلخ.',
    'admin.statusWarning': 'لن يتمكن هذا المستخدم من تسجيل الدخول حتى يتم إعادة تفعيله.',
    'admin.updateStatus': 'تحديث الحالة',
    'admin.updating': 'جاري التحديث...',
    'admin.statusActiveDesc': 'نشط - وصول كامل',
    'admin.statusSuspendedDesc': 'معلق - محظور مؤقتًا',
    'admin.statusBannedDesc': 'محظور - محظور نهائيًا',
    'admin.charts': 'الرسوم البيانية',
    'admin.revenueGrowth': 'نمو الإيرادات',
    'admin.vsLastMonth': 'مقابل الشهر الماضي',
    'admin.repeatCustomers': 'العملاء المتكررون',
    'admin.avgBookings': 'متوسط الحجوزات',
    'admin.retentionRevenue': 'إيرادات الاحتفاظ',
    'admin.fromRepeatCustomers': 'من العملاء المتكررين',
    'admin.topCarRevenue': 'إيرادات أفضل سيارة',
    'admin.revenueTrend': 'اتجاه الإيرادات (آخر 12 شهرًا)',
    'admin.weeklyRevenue': 'الإيرادات الأسبوعية (آخر 8 أسابيع)',
    'admin.bookingsByStatus': 'الحجوزات حسب الحالة',
    'admin.mostProfitableCars': 'السيارات الأكثر ربحًا',
    'admin.paymentMethods': 'طرق الدفع',
    'admin.topRepeatCustomers': 'أفضل العملاء المتكررين',
    'admin.customer': 'العميل',
    'admin.bookingsColumn': 'الحجوزات',
    'admin.totalSpentColumn': 'إجمالي الإنفاق',
    'admin.noRevenueData': 'لا توجد بيانات إيرادات متاحة',
    'admin.noWeeklyData': 'لا توجد بيانات أسبوعية متاحة',
    'admin.noBookingStatusData': 'لا توجد بيانات حالة الحجز',
    'admin.noCarBookingData': 'لا توجد بيانات حجز السيارات متاحة',
    'admin.noPaymentData': 'لا توجد بيانات دفع متاحة',
    'admin.noRepeatCustomers': 'لا يوجد عملاء متكررون بعد',
    'admin.noAnalyticsData': 'لا توجد بيانات تحليلية متاحة',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.address': 'العنوان',
    'contact.addressLine1': 'شارع احمد زكرياء رقم 132',
    'contact.addressLine2': 'بلوك ابطيح تمديد الداخلة، أكادير',
    'contact.email': 'البريد الإلكتروني',
    'contact.hours': 'ساعات العمل',
    'contact.location': 'موقعنا',
    'contact.getDirections': 'الحصول على الاتجاهات',
    'contact.findUs': 'اعثر علينا',
    'contact.visitText': 'قم بزيارتنا في مكتب تأجير السيارات. نحن هنا لمساعدتك في العثور على السيارة المثالية.',
    'contact.getInTouch': 'تواصل معنا',
    'contact.contactUs': 'اتصل بنا',
    'contact.contactSubtitle': 'هل لديك أسئلة؟ يسعدنا أن نسمع منك. أرسل لنا رسالة وسنرد في أقرب وقت ممكن.',
    'contact.contactInfo': 'معلومات الاتصال',
    'contact.phone': 'الهاتف',
    'contact.businessHours': 'ساعات العمل',
    'contact.monday': 'الاثنين - الجمعة',
    'contact.saturday': 'السبت',
    'contact.sunday': 'الأحد',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.name': 'الاسم',
    'contact.namePlaceholder': 'اسمك',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.phonePlaceholder': '+212 XXX XXX XXX',
    'contact.message': 'الرسالة',
    'contact.messagePlaceholder': 'أخبرنا كيف يمكننا مساعدتك...',
    'contact.send': 'إرسال الرسالة',
    'contact.sending': 'جاري الإرسال...',
    'contact.success': 'تم إرسال الرسالة! سنرد عليك قريبًا.',
    'contact.error': 'فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    
    // WhatsApp
    'whatsapp.contact': 'تواصل عبر واتساب',
    'whatsapp.hello': 'مرحبا، أنا مهتم بـ',
    
    // Cars Page
    'carsPage.title': 'أسطولنا',
    'carsPage.subtitle': 'ابحث واحجز سيارتك المثالية',
    'carsPage.searchPlaceholder': 'البحث بالاسم أو العلامة...',
    'carsPage.noResults': 'لا توجد سيارات تطابق الفلاتر.',
    'carsPage.all': 'الكل',
    
    // About
    'about.title': 'حول وكالة التأجير الخاصة بك',
    'about.subtitle': 'شريكك الموثوق لتأجير السيارات في المغرب',
    'about.intro': 'وكالة التأجير الخاصة بك هي وكالة مغربية لتأجير السيارات تضع العميل في قلب نشاطها. نقدم أسطولًا متنوعًا (سيارات المدينة، السيدان، الدفع الرباعي، المركبات التجارية) وخدمات مخصصة: إيجارات قصيرة ومتوسطة الأجل، خيارات مع سائق، وحلول للشركات.',
    'about.missionTitle': 'مهمتنا',
    'about.mission1': 'تسهيل تنقلاتك من خلال حجز بسيط وسريع (عبر الإنترنت أو عبر الهاتف).',
    'about.mission2': 'ضمان مركبات صيانة جيدة وموثوقة ومؤمنة.',
    'about.mission3': 'تقديم أسعار شفافة ومساعدة عملاء استباقية.',
    'about.whyTitle': 'لماذا تختارنا؟',
    'about.why1Title': 'وضوح الأسعار',
    'about.why1Text': 'لا توجد رسوم خفية، عروض أسعار مفصلة قبل التأكيد.',
    'about.why2Title': 'المرونة',
    'about.why2Text': 'مجموعة واسعة من الفئات والخيارات (مقعد الطفل، نظام تحديد المواقع، سائق إضافي، إلخ).',
    'about.why3Title': 'دعم العملاء',
    'about.why3Text': 'فريق متاح، يمكن الوصول إليه عبر البريد الإلكتروني على sihabi.cars@gmail.com.',
    'about.qualityTitle': 'التزام الجودة والسلامة',
    'about.qualityText': 'يتم فحص كل مركبة بانتظام. نحترم معايير عالية من النظافة والصيانة لضمان سلامتك وراحتك.',
    'about.contactTitle': 'اتصل بنا',
    'about.contactText': 'هل لديك أسئلة أو حاجة محددة؟ راسلنا أو قم بزيارة موقعنا.',
    
    // Terms
    'terms.title': 'الشروط والأحكام العامة',
    'terms.intro': 'من خلال الوصول إلى موقع وكالة التأجير الخاصة بك واستخدام خدمات الحجز عبر الإنترنت، فإنك توافق على هذه الشروط.',
    'terms.section1Title': 'الغرض',
    'terms.section1Text': 'يتيح الموقع تصفح الأسطول والحصول على الأسعار وتقديم طلبات الحجز. تتطلب بعض الحجوزات تأكيدًا يدويًا.',
    'terms.section2Title': 'الحساب والدقة',
    'terms.section2Text': 'أنت مسؤول عن دقة المعلومات التي تقدمها. في حالة وجود أخطاء واضحة (السعر/التوفر)، يمكن للوكالة إلغاء الطلب بعد إبلاغك.',
    'terms.section3Title': 'عملية الحجز',
    'terms.section3Item1': 'طلب عبر الإنترنت مع معلوماتك وتواريخك.',
    'terms.section3Item2': 'التحقق من التوفر.',
    'terms.section3Item3': 'تأكيد الوكالة (البريد الإلكتروني/الهاتف) والشروط التفصيلية (الوديعة، المستندات، إلخ).',
    'terms.section4Title': 'التسعير والدفع',
    'terms.section4Text': 'الأسعار المعروضة إرشادية؛ قد يشمل المبلغ النهائي خيارات/تأمينات محددة. يتم توفير طرق الدفع المقبولة عند التأكيد.',
    'terms.section5Title': 'الإلغاء والتعديلات',
    'terms.section5Text': 'يتم توفير شروط الإلغاء/التعديل عند التأكيد (المواعيد النهائية، الرسوم المحتملة).',
    'terms.section6Title': 'استخدام المركبة',
    'terms.section6Text': 'اتبع قواعد المرور، سياسة الوقود، الصيانة، وقت ومكان الإرجاع. الغرامات/الأضرار على نفقة المستأجر وفقًا لعقد الإيجار.',
    'terms.section7Title': 'المسؤولية',
    'terms.section7Text': 'قد يكون الموقع غير متاح (الصيانة/القوة القاهرة). وكالة التأجير الخاصة بك غير مسؤولة عن الأضرار غير المباشرة المتعلقة باستخدام الموقع.',
    'terms.section8Title': 'البيانات الشخصية',
    'terms.section8Text': 'تتبع معالجة البيانات سياسة الخصوصية الخاصة بنا. الاتصال: sihabi.cars@gmail.com.',
    'terms.section9Title': 'القانون الساري',
    'terms.section9Text': 'تخضع هذه الشروط للقانون المعمول به في المقر الرئيسي للوكالة.',

    // Privacy
    'privacy.title': 'سياسة الخصوصية',
    'privacy.intro': 'توضح هذه السياسة كيفية جمع وكالة التأجير لبياناتك الشخصية واستخدامها ومشاركتها وحمايتها عند استخدام موقعنا وخدمات الحجز عبر الإنترنت.',
    'privacy.section1Title': 'المسؤول عن المعالجة',
    'privacy.section1Text': 'وكالة التأجير الخاصة بك، المغرب. الاتصال: sihabi.cars@gmail.com.',
    'privacy.section2Title': 'البيانات التي نجمعها',
    'privacy.section2Item1': 'الهوية والاتصال: الاسم، البريد الإلكتروني، الهاتف، العنوان.',
    'privacy.section2Item2': 'بيانات الحجز: التواريخ، الأماكن، فئة المركبة، الخيارات.',
    'privacy.section2Item3': 'بيانات الدفع: تتم معالجتها من قبل مزودين آمنين (لا نخزن أرقام البطاقات).',
    'privacy.section2Item4': 'البيانات التقنية: عنوان IP، السجلات، ملفات تعريف الارتباط.',
    'privacy.section3Title': 'الأغراض والأسس القانونية',
    'privacy.section3Item1': 'تنفيذ العقد: إدارة الحجوزات، التواصل مع العملاء.',
    'privacy.section3Item2': 'الالتزامات القانونية: الفواتير، المحاسبة، منع الاحتيال.',
    'privacy.section3Item3': 'المصلحة المشروعة: تحسين الخدمة، إحصاءات الاستخدام.',
    'privacy.section3Item4': 'الموافقة: رسائل تسويقية إذا وافقت (إلغاء الاشتراك في أي وقت).',
    'privacy.section4Title': 'مشاركة البيانات',
    'privacy.section4Text': 'لا نبيع البيانات الشخصية. يمكننا مشاركتها مع:',
    'privacy.section4Item1': 'المزودون التقنيون (الاستضافة، الدفع، البريد الإلكتروني) الضروريون لتقديم الخدمة.',
    'privacy.section4Item2': 'السلطات العامة عند الاقتضاء القانوني.',
    'privacy.section5Title': 'الاحتفاظ بالبيانات',
    'privacy.section5Text': 'نحتفظ بالبيانات طالما كان ذلك ضروريًا لكل غرض، ثم نؤرشفها أو نحذفها بشكل آمن.',
    'privacy.section6Title': 'ملفات تعريف الارتباط',
    'privacy.section6Text': 'نستخدم ملفات تعريف الارتباط التقنية والتحليلية والتسويقية. يمكنك إدارة تفضيلاتك في متصفحك.',
    'privacy.section7Title': 'الأمان',
    'privacy.section7Text': 'نطبق تدابير تقنية وتنظيمية (التشفير أثناء النقل، ضوابط الوصول، النسخ الاحتياطية).',
    'privacy.section8Title': 'حقوقك',
    'privacy.section8Text': 'الوصول، التصحيح، الحذف، التقييد، الاعتراض، قابلية النقل. الاتصال: sihabi.cars@gmail.com.',
    'privacy.section9Title': 'النقل الدولي',
    'privacy.section9Text': 'قد يكون بعض المزودين في الخارج؛ نضمن ضمانات مناسبة (مثل البنود التعاقدية النموذجية).',
    'privacy.section10Title': 'الاتصال',
    'privacy.section10Text': 'لأي سؤال يتعلق بالخصوصية، أرسل بريدًا إلكترونيًا إلى sihabi.cars@gmail.com.',

    'search.placeholder': 'ابحث عن سيارة (الماركة، الموديل...)',
    'search.category': 'الفئة',
    'search.allCategories': 'كل الفئات',
    'search.button': 'بحث',
    'stats.clients': '+200',
    'stats.clientsLabel': 'عميل راضٍ',
    'stats.cars': '+50',
    'stats.carsLabel': 'سيارة متاحة',
    'stats.experience': '10 سنوات',
    'stats.experienceLabel': 'من الخبرة',
    'stats.cities': 'أكادير',
    'stats.citiesLabel': 'والمناطق المجاورة',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.cars': 'Cars',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    
    // Hero
    'hero.badge': 'Premium Car Rental',
    'hero.title': 'Drive Your',
    'hero.titleHighlight': 'Dream Car',
    'hero.subtitle': 'Choose from our curated collection of premium vehicles. From luxury sedans to high-performance sports cars.',
    'hero.cta': 'Browse Cars',
    
    // Home
    'home.featured': 'Featured',
    'home.popularCars': 'Popular Cars',
    'home.viewAll': 'View all',
    'home.noCars': 'No cars yet. Add some from the Admin dashboard.',
    'home.footer': '© 2026 Sihabi Cars. All rights reserved.',
    
    // Footer
    'footer.description': 'We are a Moroccan car rental company. Our agency offers a complete and varied range of vehicles to meet your mobility needs.',
    'footer.usefulLinks': 'Useful Links',
    'footer.aboutUs': 'About Us',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.payment': 'Payment Methods',
    'footer.paymentCards': 'Visa & Mastercard',
    'footer.paymentCash': 'Cash on pickup',
    'footer.paymentTransfer': 'Bank transfer',
    'footer.followUs': 'Follow Us',
    
    // Cars
    'cars.title': 'Available Cars',
    'currency': 'MAD',
    'cars.perDay': '/day',
    'cars.day': 'day',
    'cars.viewDetails': 'View Details',
    'cars.bookNow': 'Book Now',
    'cars.features': 'Features',
    'cars.specifications': 'Specifications',
    'cars.available': 'Available',
    'cars.unavailable': 'Unavailable',
    'cars.seats': 'seats',
    
    // Booking
    'booking.title': 'Book This Car',
    'booking.startDate': 'Start Date',
    'booking.endDate': 'End Date',
    'booking.totalPrice': 'Total Price',
    'booking.days': 'days',
    'booking.confirm': 'Confirm Booking',
    'booking.success': 'Booking confirmed successfully!',
    'booking.error': 'Booking error',
    'booking.loginRequired': 'Please login to book',
    'booking.cin': 'CIN',
    'booking.cinPlaceholder': 'CIN Number',
    'booking.driverLicense': 'Driver License',
    'booking.driverLicensePlaceholder': 'License Number',
    'booking.paymentMethod': 'Preferred Payment Method',
    'booking.paymentNote': 'Payment will be made at vehicle pickup',
    'booking.cash': 'Cash',
    'booking.card': 'Card',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.edit': 'Edit',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.city': 'City',
    'profile.myBookings': 'My Bookings',
    'profile.noBookings': 'No bookings',
    'profile.booking': 'Booking',
    'profile.bookings': 'Bookings',
    'profile.bookingId': 'Booking #',
    'profile.dates': 'Dates',
    'profile.total': 'Total',
    'profile.payment': 'Payment',
    'profile.rentalPeriod': 'Rental Period',
    'profile.to': 'to',
    'profile.totalPrice': 'Total Price',
    'profile.paymentMethod': 'Payment Method',
    'profile.bookedOn': 'Booked On',
    'profile.status.pending': 'Pending',
    'profile.status.confirmed': 'Confirmed',
    'profile.status.completed': 'Completed',
    'profile.status.cancelled': 'Cancelled',
    'profile.bookingConfirmed': 'Booking Confirmed',
    'profile.bookingConfirmedText': 'This booking has been confirmed by the admin. To cancel, please contact us at',
    'profile.orCall': 'or call',
    'profile.cancelBooking': 'Cancel Booking',
    'profile.keepBooking': 'Keep Booking',
    'profile.cancelBookingTitle': 'Cancel Booking?',
    'profile.cancelBookingConfirm': 'Are you sure you want to cancel this booking for',
    'profile.cancelBookingWarning': 'This action cannot be undone.',
    'profile.yesCancelBooking': 'Yes, Cancel Booking',
    'profile.bookingCancelledSuccess': 'Booking cancelled successfully!',
    'profile.bookingCancelledError': 'Failed to cancel booking',
    
    // Auth
    'auth.account': 'Account',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.register': 'Register',
    'auth.createAccount': 'Create account',
    'auth.firstName': 'First name',
    'auth.lastName': 'Last name',
    'auth.phone': 'Phone',
    'auth.city': 'City',
    'auth.passwordMin': 'Min. 8 characters',
    'auth.phonePlaceholder': '+212 6XX XXX XXX',
    'auth.noAccount': "Don't have an account?",
    'auth.registerHere': 'Register here',
    'auth.haveAccount': 'Already have an account?',
    'auth.loginHere': 'Login here',
    'auth.forgotPassword': 'Forgot password?',
    'auth.forgotPasswordSubtitle': 'Enter your email and we\'ll send you a reset link',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.backToLogin': 'Back to Login',
    'auth.emailSent': 'Check Your Email',
    'auth.emailSentMessage': 'We\'ve sent a password reset link to',
    'auth.emailSentNote': 'Click the link in the email to reset your password. The link will expire in 1 hour.',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordSubtitle': 'Enter your new password below',
    'auth.newPassword': 'New Password',
    'auth.invalidLink': 'Invalid Reset Link',
    'auth.invalidLinkMessage': 'This password reset link is invalid or has expired. Please request a new one.',
    'auth.requestNewLink': 'Request New Link',
    'auth.passwordReset': 'Password Reset!',
    'auth.passwordResetMessage': 'Your password has been successfully reset. You can now login with your new password.',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.analytics': 'Analytics',
    'admin.carsTab': 'Cars',
    'admin.bookingsTab': 'Bookings',
    'admin.usersTab': 'Users',
    'admin.messagesTab': 'Messages',
    'admin.cars': 'Car Management',
    'admin.bookings': 'Booking Management',
    'admin.addCar': 'Add Car',
    'admin.addNewCar': 'Add New Car',
    'admin.editCar': 'Edit Car',
    'admin.saveCar': 'Save Car',
    'admin.saving': 'Saving...',
    'admin.saveChanges': 'Save Changes',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.brand': 'Brand',
    'admin.name': 'Name',
    'admin.price': 'Price',
    'admin.actions': 'Actions',
    'admin.dailyRevenue': 'Daily Revenue',
    'admin.today': 'Today',
    'admin.yesterday': 'Yesterday',
    'admin.monthlyRevenue': 'Monthly Revenue',
    'admin.thisMonth': 'This Month',
    'admin.lastMonth': 'Last Month',
    'admin.yearlyRevenue': 'Yearly Revenue',
    'admin.thisYear': 'This Year',
    'admin.lastYear': 'Last Year',
    'admin.totalRevenue': 'Total Revenue',
    'admin.allTime': 'All Time',
    'admin.totalBookings': 'Total Bookings',
    'admin.totalUsers': 'Total Users',
    'admin.totalCars': 'Total Cars',
    'admin.car': 'Car',
    'admin.category': 'Category',
    'admin.status': 'Status',
    'admin.available': 'Available',
    'admin.unavailable': 'Unavailable',
    'admin.featuredHomepage': 'Featured on Homepage',
    'admin.imageUrl': 'Image URL',
    'admin.uploadImages': 'Upload Images',
    'admin.description': 'Description',
    'admin.seats': 'Seats',
    'admin.transmission': 'Transmission',
    'admin.automatic': 'Automatic',
    'admin.manual': 'Manual',
    'admin.fuelType': 'Fuel Type',
    'admin.gasoline': 'Gasoline',
    'admin.diesel': 'Diesel',
    'admin.electric': 'Electric',
    'admin.hybrid': 'Hybrid',
    'admin.noCars': 'No cars yet',
    'admin.customer': 'Customer',
    'admin.dates': 'Dates',
    'admin.total': 'Total',
    'admin.payment': 'Payment',
    'admin.cash': 'Cash',
    'admin.card': 'Card',
    'admin.pending': 'Pending',
    'admin.confirmed': 'Confirmed',
    'admin.completed': 'Completed',
    'admin.noBookings': 'No bookings yet',
    'admin.noBookingsSearch': 'No bookings match your search',
    'admin.searchBookings': 'Search by customer, car, or booking ID...',
    'admin.refresh': 'Refresh',
    'admin.customerInfo': 'Customer Information',
    'admin.bookingDetails': 'Booking Details',
    'admin.bookingId': 'Booking ID',
    'admin.totalPrice': 'Total Price',
    'admin.contactInfo': 'Contact Information',
    'admin.emailLabel': 'Email',
    'admin.phone': 'Phone',
    'admin.registeredUser': 'Registered User Account',
    'admin.accountName': 'Account Name',
    'admin.accountEmail': 'Account Email',
    'admin.accountPhone': 'Account Phone',
    'admin.city': 'City',
    'admin.bookedOn': 'Booked on',
    'admin.user': 'User',
    'admin.contact': 'Contact',
    'admin.role': 'Role',
    'admin.roleUser': 'User',
    'admin.roleAdmin': 'Admin',
    'admin.bookingsCount': 'Bookings',
    'admin.totalSpent': 'Total Spent',
    'admin.joined': 'Joined',
    'admin.noUsers': 'No users yet',
    'admin.noUsersSearch': 'No users match your search',
    'admin.searchUsers': 'Search by name, email, or city...',
    'admin.editUser': 'Edit User',
    'admin.statistics': 'Statistics',
    'admin.totalBookingsReadOnly': 'Total Bookings (Read-only)',
    'admin.totalSpentLabel': 'Total Spent ($)',
    'admin.from': 'From',
    'admin.message': 'Message',
    'admin.date': 'Date',
    'admin.unread': 'Unread',
    'admin.read': 'Read',
    'admin.replied': 'Replied',
    'admin.noMessages': 'No messages yet',
    'admin.accountStatus': 'Account Status',
    'admin.accountActive': 'Active',
    'admin.accountSuspended': 'Suspended',
    'admin.accountBanned': 'Banned',
    'admin.changeStatus': 'Change Status',
    'admin.statusReason': 'Reason (Optional)',
    'admin.statusReasonPlaceholder': 'e.g., Multiple failed payments, Terms violation, etc.',
    'admin.statusWarning': 'This user will not be able to login until reactivated.',
    'admin.updateStatus': 'Update Status',
    'admin.updating': 'Updating...',
    'admin.statusActiveDesc': 'Active - Full access',
    'admin.statusSuspendedDesc': 'Suspended - Temporarily blocked',
    'admin.statusBannedDesc': 'Banned - Permanently blocked',
    'admin.charts': 'Charts',
    'admin.revenueGrowth': 'Revenue Growth',
    'admin.vsLastMonth': 'vs last month',
    'admin.repeatCustomers': 'Repeat Customers',
    'admin.avgBookings': 'avg bookings',
    'admin.retentionRevenue': 'Retention Revenue',
    'admin.fromRepeatCustomers': 'from repeat customers',
    'admin.topCarRevenue': 'Top Car Revenue',
    'admin.revenueTrend': 'Revenue Trend (Last 12 Months)',
    'admin.weeklyRevenue': 'Weekly Revenue (Last 8 Weeks)',
    'admin.bookingsByStatus': 'Bookings by Status',
    'admin.mostProfitableCars': 'Most Profitable Cars',
    'admin.paymentMethods': 'Payment Methods',
    'admin.topRepeatCustomers': 'Top Repeat Customers',
    'admin.customer': 'Customer',
    'admin.bookingsColumn': 'Bookings',
    'admin.totalSpentColumn': 'Total Spent',
    'admin.noRevenueData': 'No revenue data available',
    'admin.noWeeklyData': 'No weekly data available',
    'admin.noBookingStatusData': 'No booking status data',
    'admin.noCarBookingData': 'No car booking data available',
    'admin.noPaymentData': 'No payment data available',
    'admin.noRepeatCustomers': 'No repeat customers yet',
    'admin.noAnalyticsData': 'No analytics data available',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.address': 'Address',
    'contact.addressLine1': '132 Ahmed Zakaria Street',
    'contact.addressLine2': 'Abtih Block Dakhla Extension, Agadir',
    'contact.email': 'Email',
    'contact.hours': 'Opening Hours',
    'contact.location': 'Our Location',
    'contact.getDirections': 'Get Directions',
    'contact.findUs': 'Find Us',
    'contact.visitText': 'Visit us at our car rental office. We\'re here to help you find the perfect vehicle.',
    'contact.getInTouch': 'Get in Touch',
    'contact.contactUs': 'Contact Us',
    'contact.contactSubtitle': 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.contactInfo': 'Contact Information',
    'contact.phone': 'Phone',
    'contact.businessHours': 'Business Hours',
    'contact.monday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.sendMessage': 'Send us a Message',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.phonePlaceholder': '+212 XXX XXX XXX',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent! We\'ll get back to you soon.',
    'contact.error': 'Failed to send message. Please try again.',
    
    // WhatsApp
    'whatsapp.contact': 'Contact via WhatsApp',
    'whatsapp.hello': 'Hello, I\'m interested in',
    
    // Cars Page
    'carsPage.title': 'Our Fleet',
    'carsPage.subtitle': 'Find and book your perfect ride',
    'carsPage.searchPlaceholder': 'Search by car name or brand...',
    'carsPage.noResults': 'No cars match your filters.',
    'carsPage.all': 'All',
    
    // About
    'about.title': 'About Your Rental Agency',
    'about.subtitle': 'Your trusted partner for car rental in Morocco',
    'about.intro': 'Your Rental Agency is a Moroccan car rental agency that places the customer at the heart of its activity. We offer a diversified fleet (city cars, sedans, SUVs, commercial vehicles) and tailored services: short and medium-term rentals, options with driver, and solutions for businesses.',
    'about.missionTitle': 'Our Mission',
    'about.mission1': 'Facilitate your travels with simple and fast booking (online or by phone).',
    'about.mission2': 'Guarantee maintained, reliable and insured vehicles.',
    'about.mission3': 'Offer transparent pricing and proactive customer assistance.',
    'about.whyTitle': 'Why Choose Us?',
    'about.why1Title': 'Price Clarity',
    'about.why1Text': 'No hidden fees, detailed quotes before confirmation.',
    'about.why2Title': 'Flexibility',
    'about.why2Text': 'Wide choice of categories and options (baby seat, GPS, additional driver, etc.).',
    'about.why3Title': 'Customer Support',
    'about.why3Text': 'A responsive team, reachable by email at sihabi.cars@gmail.com.',
    'about.qualityTitle': 'Quality & Safety Commitment',
    'about.qualityText': 'Each vehicle is inspected regularly. We respect high standards of hygiene and maintenance to guarantee your safety and comfort.',
    'about.contactTitle': 'Contact Us',
    'about.contactText': 'Questions or specific needs? Write to us or visit our website.',
    
    // Terms
    'terms.title': 'Terms & Conditions',
    'terms.intro': 'By accessing the Your Rental Agency website and using our online booking services, you agree to these terms.',
    'terms.section1Title': 'Purpose',
    'terms.section1Text': 'The website allows browsing the fleet, getting prices, and submitting booking requests. Some bookings require manual confirmation.',
    'terms.section2Title': 'Account & Accuracy',
    'terms.section2Text': 'You are responsible for the accuracy of the information you provide. In case of obvious errors (price/availability), the Agency may cancel the request after informing you.',
    'terms.section3Title': 'Booking Process',
    'terms.section3Item1': 'Online request with your information and dates.',
    'terms.section3Item2': 'Availability check.',
    'terms.section3Item3': 'Agency confirmation (email/phone) and detailed terms (deposit, documents, etc.).',
    'terms.section4Title': 'Pricing & Payment',
    'terms.section4Text': 'Displayed prices are indicative; the final amount may include selected options/insurances. Accepted payment methods are provided upon confirmation.',
    'terms.section5Title': 'Cancellation & Changes',
    'terms.section5Text': 'Cancellation/change conditions are provided at confirmation (deadlines, possible fees).',
    'terms.section6Title': 'Vehicle Use',
    'terms.section6Text': 'Follow traffic rules, fuel policy, maintenance, return time and location. Fines/damages are at the renter\'s expense per the rental agreement.',
    'terms.section7Title': 'Liability',
    'terms.section7Text': 'The site may be unavailable (maintenance/force majeure). Your Rental Agency is not liable for indirect damages related to site usage.',
    'terms.section8Title': 'Personal Data',
    'terms.section8Text': 'Data processing follows our Privacy Policy. Contact: sihabi.cars@gmail.com.',
    'terms.section9Title': 'Governing Law',
    'terms.section9Text': 'These terms are governed by the law applicable at the Agency\'s registered office.',

    // Privacy
    'privacy.title': 'Privacy Policy',
    'privacy.intro': 'This policy explains how Your Rental Agency collects, uses, shares, and protects your personal data when you use our website and online booking services.',
    'privacy.section1Title': 'Data Controller',
    'privacy.section1Text': 'Your Rental Agency, Morocco. Contact: sihabi.cars@gmail.com.',
    'privacy.section2Title': 'Data We Collect',
    'privacy.section2Item1': 'Identity & contact: name, email, phone, address.',
    'privacy.section2Item2': 'Booking data: dates, locations, vehicle category, options.',
    'privacy.section2Item3': 'Payment data: processed by secure providers (we do not store card numbers).',
    'privacy.section2Item4': 'Technical data: IP address, logs, cookies.',
    'privacy.section3Title': 'Purposes & Legal Bases',
    'privacy.section3Item1': 'Contract performance: booking management, customer communication.',
    'privacy.section3Item2': 'Legal obligations: invoicing, accounting, fraud prevention.',
    'privacy.section3Item3': 'Legitimate interest: service improvement, usage statistics.',
    'privacy.section3Item4': 'Consent: marketing emails if you consent (unsubscribe at any time).',
    'privacy.section4Title': 'Data Sharing',
    'privacy.section4Text': 'We do not sell personal data. We may share it with:',
    'privacy.section4Item1': 'Technical providers (hosting, payment, email) strictly necessary to deliver the service.',
    'privacy.section4Item2': 'Public authorities when required by law.',
    'privacy.section5Title': 'Retention',
    'privacy.section5Text': 'We retain data as long as necessary for each purpose, then archive or securely delete it.',
    'privacy.section6Title': 'Cookies',
    'privacy.section6Text': 'We use technical, analytical, and marketing cookies. You can manage your preferences in your browser.',
    'privacy.section7Title': 'Security',
    'privacy.section7Text': 'We implement technical and organisational measures (encryption in transit, access controls, backups).',
    'privacy.section8Title': 'Your Rights',
    'privacy.section8Text': 'Access, rectification, deletion, restriction, objection, portability. Contact: sihabi.cars@gmail.com.',
    'privacy.section9Title': 'International Transfers',
    'privacy.section9Text': 'Some providers may be located abroad; we ensure appropriate safeguards (e.g. standard contractual clauses).',
    'privacy.section10Title': 'Contact',
    'privacy.section10Text': 'For any privacy-related question, email sihabi.cars@gmail.com.',

    'search.placeholder': 'Search a car (brand, model...)',
    'search.category': 'Category',
    'search.allCategories': 'All categories',
    'search.button': 'Search',
    'stats.clients': '+200',
    'stats.clientsLabel': 'Happy Clients',
    'stats.cars': '+50',
    'stats.carsLabel': 'Vehicles Available',
    'stats.experience': '10 Years',
    'stats.experienceLabel': 'Of Experience',
    'stats.cities': 'Agadir',
    'stats.citiesLabel': '& Surroundings',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
